### PR TITLE
Expand timestamps for std_msgs.msg.Header and builtin_interfaces.msg.Time if 'auto' and 'now' are passed as values

### PR DESCRIPTION
**Pull request by esteve**
Merge the logic from https://github.com/ros2/ros2cli/pull/749 into `set_message_fields`

Closes https://github.com/ros2/ros2cli/issues/700

### CODE REVIEW

**Review by ivanpauno — APPROVED** [review]
LGTM!

The change seems fine to me, it's backwards compatible, even if it adds a return value to the function.
It would be good to move the test cases here as well.

I will tag one of the maintainers of this package for review.

**Review by fujitatomoya — APPROVED** [review]

**Comment by esteve** [comment]
@ivanpauno I've updated this PR with the tests from https://github.com/ros2/ros2cli/pull/749

**Review by ivanpauno — APPROVED** [review]
LGTM

**Comment by ivanpauno** [comment]
@sloretz could you take a look to this PR?

**Review by sloretz — COMMENTED** [review]
This looks really useful! I recommend adding test cases for when `now` and `auto` are used but `expand_header_auto` and `expeand_time_now` are False, but I won't block on that.

**Comment by esteve** [comment]
@sloretz sounds good, I'll add those tests here and in #20

**Comment by esteve** [comment]
@sloretz I've added the tests in https://github.com/ros2/rosidl_runtime_py/pull/19/commits/5c10bf6b4c6c06e7ed71a4f8fc7c4b7ef09eb2a7

**Review by ivanpauno — APPROVED** [review]

**Comment by ivanpauno** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/17279/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/11819/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/17760/)

**Comment by ivanpauno** [comment]
@esteve could you fix the flake8 failures?

**Comment by esteve** [comment]
@ivanpauno done in https://github.com/ros2/rosidl_runtime_py/pull/19/commits/9e07e52d439779cdce1a04eff8344559127b35dc The import order does not look pretty IMHO, but it makes flake8 happy.

**Comment by ivanpauno** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/17289/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/11830/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/17774/)

**Pull request merged**
