### PR TITLE
Migrate package files from rosidl_python

### PR DESCRIPTION
**Pull request by jacobperron**
Previously located at https://github.com/ros2/rosidl_python.git

This helps removes a circular dependency between repositories.

### CODE REVIEW

**Comment by jacobperron** [comment]
> The move needs to preserve the history of the package.

My bad, will do.

**Comment by jacobperron** [comment]
@dirk-thomas I've run `git filter-branch --subdirectory-filter rosidl_runtime_py -- --all` and pushed to master. I add another commit adding the missing contributing and license files.

**Comment by dirk-thomas** [comment]
Just a note: all commit messages reference (not-existing) tickets in this repo then. Not sure if it is worth rewriting the messages.

**Comment by jacobperron** [comment]
It wasn't too much effort to rewrite. Let me know if it looks reasonable: https://github.com/ros2/rosidl_runtime_py/commits/master

**Comment by dirk-thomas** [comment]
> It wasn't too much effort to rewrite.

:+1: great!

**Comment by jacobperron** [comment]
> Hmm, I only migrated master and not --all when I did the python_cmake_module migration. I figured any existing branches (like dashing) would continue to be used only on the original repository.

I probably could have just done that as well. In any case, there was only `master` for `rosidl_runtime_py`.

**Pull request closed without merging**
