### PR TITLE
[humble] Backport. Expand timestamps for std_msgs.msg.Header and builtin_interfaces.msg.Time if 'auto' and 'now' are passed as values

### PR DESCRIPTION
**Pull request by esteve**
Backport of #19

### CODE REVIEW

**Comment by ivanpauno** [comment]
Let's wait until #19 gets merged

**Review by fujitatomoya — APPROVED** [review]

**Comment by esteve** [comment]
@fujitatomoya @ivanpauno this PR is now ready for review, the same changes in #19 have been merged into `rolling`

**Review by ivanpauno — APPROVED** [review]
LGTM!

**Comment by ivanpauno** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/17298/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/11838/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/17784/)

**Pull request merged**
