### PR TITLE
Add .gitignore

### PR DESCRIPTION
**Pull request by galou**

### CODE REVIEW

**Comment by mjcarroll** [comment]
For consistency, we should also ignore `*.pyc`, as we do in other python repositories.

Also, you will need to signoff your commits by doing `git commit -s` in order to pass DCO checks.

**Comment by galou** [comment]
Is Python2 supported is ROS2?

**Comment by mjcarroll** [comment]
It is not.  Purely Python3.

**Comment by mjcarroll** [comment]
Oh yes, I see what you are saying, `__pycache__` should be sufficient in python3.  Just a signoff, then.

**Comment by galou** [comment]
Signed-off.

**Pull request merged**
